kind: Service                             
apiVersion: v1
metadata:
  name: karammajdi
  labels:
    app: karammajdi
spec:
  ports:
    - port: 8000                               
      targetPort: 8000                    
      nodePort: 31200
  selector:
    app: karammajdi                    
  type: LoadBalancer  